### ISSUE TITLE
Bug - buton logare

### ISSUE THREAD

**Issue by Gabor132** [AlexandruGhergut/BattleAI#48]
Am identificat un bug la logare, se bloca interfata dupa apasarea butonului de login pentru ca dadea o exceptie la conectarea la master server, insa acuma nu mai face, nu stiu daca e din cauza mea. De investigat.

P.S : Fain ar fi daca am pune bug-urile gasite pe aici

**Comment by AlexandruGhergut** [comment]
This should be fixed now.
